### ISSUE TITLE
Permissionslist for shares missing definition 

### ISSUE THREAD

**Issue by Oscarhewittlindberg** [databricks/databricks-sdk-py#224]
**Description**
The return of a single shares not possible due to missing definition for Permissionslist. 

**Reproduction**

```python
w.shares.share_permissions(name=<share_name>)

```  
response:
```
   1324     request = SharePermissionsRequest(name=name)
   1326 json = self._api.do('GET', f'/api/2.1/unity-catalog/shares/{request.name}/permissions')
-> 1327 return PermissionsList.from_dict(json)

NameError: name 'PermissionsList' is not defined
``` 

**Expected behavior**
An permissionslist object 

**Other Information**
missing class affil in method in databricks/sdk/service/SharesAPI - share_permissions:

```python
    def share_permissions(self, name: str, **kwargs) -> catalog.PermissionsList:
        """Get permissions.
        
        Gets the permissions for a data share from the metastore. The caller must be a metastore admin or the
        owner of the share.
        
        :param name: str
          The name of the share.
        
        :returns: :class:`PermissionsList`
        """
        request = kwargs.get('request', None)
        if not request: # request is not given through keyed args
            request = SharePermissionsRequest(name=name)

        json = self._api.do('GET', f'/api/2.1/unity-catalog/shares/{request.name}/permissions')
        return >> PermissionsList.from_dict(json)
```

**Comment by rakshitpandit** [comment]
Hi @Oscarhewittlindberg, I have fixed this issue. Below is the PR for this. Please check and merge if you see fit.
https://github.com/databricks/databricks-sdk-py/pull/228

PS- This is my first open source contribution. Kindly let me know if the fix is appropriate or not.

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by adamsxs** [comment]
@nfx hello! Reaching out since this NameError is still reproducible in `databricks-sdk==0.25.1`. Would it be possible to re-open the issue as long as the NameError persists just for visibility's sake? Or was it closed since this code is auto-generated and can't be fixed by a contribution? (see #228)
